name: Github build workflow

on:
  push:
    branches:
      - main
      - dev
      - gh-pages

jobs:
  # Build the app
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
