name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          path: ./build